import { Request, Response } from 'express';
import { CategoryService } from '../services/category.service';
import { CatalogueQcService } from '../services/catalogueQc.service';
import { hasAdminPermission } from '../constants/adminRoles';

const getActor = (req: Request) => ({
  uid: req.user?.uid || 'unknown',
  email: req.user?.email,
});

const sendCategoryMutationError = (res: Response, error: any, fallbackMessage: string): void => {
  if (error.message === 'category not found') {
    res.status(404).json({
      success: false,
      message: 'Category not found'
    });
    return;
  }

  if (error.message === 'A category with this name or slug already exists' || error.code === 11000) {
    const field = error.keyPattern?.name ? 'name' : 'slug';
    res.status(409).json({
      success: false,
      message: error.message || `A category with this ${field} already exists`
    });
    return;
  }

  if (error.name === 'ValidationError') {
    const messages = Object.values(error.errors).map((err: any) => err.message);
    res.status(400).json({
      success: false,
      message: 'Validation failed',
      errors: messages
    });
    return;
  }

  res.status(500).json({
    success: false,
    message: fallbackMessage,
    error: process.env.NODE_ENV === 'development' ? error.message : undefined
  });
};

/**
 * Create a new category
 * POST /api/v1/categories
 */
export const createCategory = async (req: Request, res: Response): Promise<void> => {
  try {
    const { name, description, isActive, fieldTemplate } = req.body;

    const categoryData = {
      name,
      description,
      slug: req.body.slug, // Generated by validator
      isActive: isActive !== undefined ? isActive : true,
      fieldTemplate: fieldTemplate || null
    };

    if (!hasAdminPermission(req.user, 'OWNER')) {
      const request = await CatalogueQcService.createRequest('category', 'create', categoryData, getActor(req));
      res.status(202).json({
        success: true,
        message: 'Category submitted for QC approval',
        data: request
      });
      return;
    }

    const category = await CategoryService.createCategory(categoryData);

    res.status(201).json({
      success: true,
      message: 'Category created successfully',
      data: category
    });
  } catch (error: any) {
    console.error('Error creating category:', error);

    sendCategoryMutationError(res, error, 'Failed to create category');
  }
};

/**
 * Get all categories with pagination
 * GET /api/v1/categories
 */
export const getAllCategories = async (req: Request, res: Response): Promise<void> => {
  try {
    const page = parseInt(req.query.page as string) || 1;
    const limit = parseInt(req.query.limit as string) || 10;
    const search = req.query.search as string;

    const result = await CategoryService.getAllCategories(page, limit, search);

    res.status(200).json({
      success: true,
      data: result.categories,
      pagination: {
        page: result.page,
        limit,
        total: result.total,
        totalPages: result.totalPages
      }
    });
  } catch (error: any) {
    console.error('Error fetching categories:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch categories',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

/**
 * Get category by ID
 * GET /api/v1/categories/:id
 */
export const getCategoryById = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;

    const category = await CategoryService.getCategoryById(id);

    if (!category) {
      res.status(404).json({
        success: false,
        message: 'Category not found'
      });
      return;
    }

    res.status(200).json({
      success: true,
      data: category
    });
  } catch (error: any) {
    console.error('Error fetching category:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch category',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

/**
 * Get category by slug
 * GET /api/v1/categories/slug/:slug
 */
export const getCategoryBySlug = async (req: Request, res: Response): Promise<void> => {
  try {
    const { slug } = req.params;

    const category = await CategoryService.getCategoryBySlug(slug);

    if (!category) {
      res.status(404).json({
        success: false,
        message: 'Category not found'
      });
      return;
    }

    res.status(200).json({
      success: true,
      data: category
    });
  } catch (error: any) {
    console.error('Error fetching category:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch category',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

/**
 * Update category
 * PUT /api/v1/categories/:id
 */
export const updateCategory = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;
    const { name, description, isActive, fieldTemplate } = req.body;

    const updateData: any = {};
    if (name) updateData.name = name;
    if (description !== undefined) updateData.description = description;
    if (isActive !== undefined) updateData.isActive = isActive;
    if (fieldTemplate !== undefined) updateData.fieldTemplate = fieldTemplate;
    if (req.body.slug) updateData.slug = req.body.slug;

    if (!hasAdminPermission(req.user, 'OWNER')) {
      const request = await CatalogueQcService.createRequest('category', 'update', updateData, getActor(req), id);
      res.status(202).json({
        success: true,
        message: 'Category changes submitted for QC approval',
        data: request
      });
      return;
    }

    const category = await CategoryService.updateCategory(id, updateData);

    if (!category) {
      res.status(404).json({
        success: false,
        message: 'Category not found'
      });
      return;
    }

    res.status(200).json({
      success: true,
      message: 'Category updated successfully',
      data: category
    });
  } catch (error: any) {
    console.error('Error updating category:', error);

    sendCategoryMutationError(res, error, 'Failed to update category');
  }
};

/**
 * Delete category
 * DELETE /api/v1/categories/:id
 */
export const deleteCategory = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;

    if (!hasAdminPermission(req.user, 'OWNER')) {
      const request = await CatalogueQcService.createRequest('category', 'delete', null, getActor(req), id);
      res.status(202).json({
        success: true,
        message: 'Category deletion submitted for QC approval',
        data: request
      });
      return;
    }

    const result = await CategoryService.deleteCategory(id);

    if (!result.success) {
      res.status(400).json({
        success: false,
        message: result.message
      });
      return;
    }

    res.status(200).json({
      success: true,
      message: 'Category deleted successfully'
    });
  } catch (error: any) {
    console.error('Error deleting category:', error);
    sendCategoryMutationError(res, error, 'Failed to delete category');
  }
};
