import { Request, Response } from 'express';
import Tag from '../models/tag.model';

/**
 * Create a new tag
 * POST /api/v1/tags
 */
export const createTag = async (req: Request, res: Response): Promise<void> => {
  try {
    const { name } = req.body;

    const tag = await Tag.create({
      name,
      slug: req.body.slug // Generated by validator
    });

    res.status(201).json({
      success: true,
      message: 'Tag created successfully',
      data: tag
    });
  } catch (error: any) {
    console.error('Error creating tag:', error);

    if (error.code === 11000) {
      res.status(409).json({
        success: false,
        message: 'A tag with this name already exists'
      });
      return;
    }

    if (error.name === 'ValidationError') {
      const messages = Object.values(error.errors).map((err: any) => err.message);
      res.status(400).json({
        success: false,
        message: 'Validation failed',
        errors: messages
      });
      return;
    }

    res.status(500).json({
      success: false,
      message: 'Failed to create tag',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

/**
 * Get all tags (no pagination needed)
 * GET /api/v1/tags
 */
export const getAllTags = async (_req: Request, res: Response): Promise<void> => {
  try {
    const tags = await Tag.find().sort({ name: 1 });

    res.status(200).json({
      success: true,
      data: tags
    });
  } catch (error: any) {
    console.error('Error fetching tags:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch tags',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

/**
 * Get tag by ID
 * GET /api/v1/tags/:id
 */
export const getTagById = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;

    const tag = await Tag.findById(id);

    if (!tag) {
      res.status(404).json({
        success: false,
        message: 'Tag not found'
      });
      return;
    }

    res.status(200).json({
      success: true,
      data: tag
    });
  } catch (error: any) {
    console.error('Error fetching tag:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch tag',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

/**
 * Update tag
 * PUT /api/v1/tags/:id
 */
export const updateTag = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;
    const { name } = req.body;

    const updateData: any = {};
    if (name) updateData.name = name;
    if (req.body.slug) updateData.slug = req.body.slug;

    const tag = await Tag.findByIdAndUpdate(id, updateData, { new: true, runValidators: true });

    if (!tag) {
      res.status(404).json({
        success: false,
        message: 'Tag not found'
      });
      return;
    }

    res.status(200).json({
      success: true,
      message: 'Tag updated successfully',
      data: tag
    });
  } catch (error: any) {
    console.error('Error updating tag:', error);

    if (error.code === 11000) {
      res.status(409).json({
        success: false,
        message: 'A tag with this name already exists'
      });
      return;
    }

    if (error.name === 'ValidationError') {
      const messages = Object.values(error.errors).map((err: any) => err.message);
      res.status(400).json({
        success: false,
        message: 'Validation failed',
        errors: messages
      });
      return;
    }

    res.status(500).json({
      success: false,
      message: 'Failed to update tag',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

/**
 * Delete tag
 * DELETE /api/v1/tags/:id
 */
export const deleteTag = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;

    const tag = await Tag.findByIdAndDelete(id);

    if (!tag) {
      res.status(404).json({
        success: false,
        message: 'Tag not found'
      });
      return;
    }

    res.status(200).json({
      success: true,
      message: 'Tag deleted successfully'
    });
  } catch (error: any) {
    console.error('Error deleting tag:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to delete tag',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

