import { Request, Response } from 'express';
import Tag from '../models/tag.model';
import { CatalogueQcService } from '../services/catalogueQc.service';
import { hasAdminPermission } from '../constants/adminRoles';

const getActor = (req: Request) => ({
  uid: req.user?.uid || 'unknown',
  email: req.user?.email,
});

const sendTagMutationError = (res: Response, error: any, fallbackMessage: string): void => {
  if (error.message === 'tag not found') {
    res.status(404).json({
      success: false,
      message: 'Tag not found'
    });
    return;
  }

  if (error.message === 'A tag with this name or slug already exists' || error.code === 11000) {
    res.status(409).json({
      success: false,
      message: error.message || 'A tag with this name already exists'
    });
    return;
  }

  if (error.name === 'ValidationError') {
    const messages = Object.values(error.errors).map((err: any) => err.message);
    res.status(400).json({
      success: false,
      message: 'Validation failed',
      errors: messages
    });
    return;
  }

  res.status(500).json({
    success: false,
    message: fallbackMessage,
    error: process.env.NODE_ENV === 'development' ? error.message : undefined
  });
};

/**
 * Create a new tag
 * POST /api/v1/tags
 */
export const createTag = async (req: Request, res: Response): Promise<void> => {
  try {
    const { name } = req.body;

    const tagData = {
      name,
      slug: req.body.slug // Generated by validator
    };

    if (!hasAdminPermission(req.user, 'OWNER')) {
      const request = await CatalogueQcService.createRequest('tag', 'create', tagData, getActor(req));
      res.status(202).json({
        success: true,
        message: 'Tag submitted for QC approval',
        data: request
      });
      return;
    }

    const tag = await Tag.create(tagData);

    res.status(201).json({
      success: true,
      message: 'Tag created successfully',
      data: tag
    });
  } catch (error: any) {
    console.error('Error creating tag:', error);

    sendTagMutationError(res, error, 'Failed to create tag');
  }
};

/**
 * Get all tags (no pagination needed)
 * GET /api/v1/tags
 */
export const getAllTags = async (_req: Request, res: Response): Promise<void> => {
  try {
    const tags = await Tag.find().sort({ name: 1 });

    res.status(200).json({
      success: true,
      data: tags
    });
  } catch (error: any) {
    console.error('Error fetching tags:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch tags',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

/**
 * Get tag by ID
 * GET /api/v1/tags/:id
 */
export const getTagById = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;

    const tag = await Tag.findById(id);

    if (!tag) {
      res.status(404).json({
        success: false,
        message: 'Tag not found'
      });
      return;
    }

    res.status(200).json({
      success: true,
      data: tag
    });
  } catch (error: any) {
    console.error('Error fetching tag:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to fetch tag',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
};

/**
 * Update tag
 * PUT /api/v1/tags/:id
 */
export const updateTag = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;
    const { name } = req.body;

    const updateData: any = {};
    if (name) updateData.name = name;
    if (req.body.slug) updateData.slug = req.body.slug;

    if (!hasAdminPermission(req.user, 'OWNER')) {
      const request = await CatalogueQcService.createRequest('tag', 'update', updateData, getActor(req), id);
      res.status(202).json({
        success: true,
        message: 'Tag changes submitted for QC approval',
        data: request
      });
      return;
    }

    const tag = await Tag.findByIdAndUpdate(id, updateData, { new: true, runValidators: true });

    if (!tag) {
      res.status(404).json({
        success: false,
        message: 'Tag not found'
      });
      return;
    }

    res.status(200).json({
      success: true,
      message: 'Tag updated successfully',
      data: tag
    });
  } catch (error: any) {
    console.error('Error updating tag:', error);

    sendTagMutationError(res, error, 'Failed to update tag');
  }
};

/**
 * Delete tag
 * DELETE /api/v1/tags/:id
 */
export const deleteTag = async (req: Request, res: Response): Promise<void> => {
  try {
    const { id } = req.params;

    if (!hasAdminPermission(req.user, 'OWNER')) {
      const request = await CatalogueQcService.createRequest('tag', 'delete', null, getActor(req), id);
      res.status(202).json({
        success: true,
        message: 'Tag deletion submitted for QC approval',
        data: request
      });
      return;
    }

    const tag = await Tag.findByIdAndDelete(id);

    if (!tag) {
      res.status(404).json({
        success: false,
        message: 'Tag not found'
      });
      return;
    }

    res.status(200).json({
      success: true,
      message: 'Tag deleted successfully'
    });
  } catch (error: any) {
    console.error('Error deleting tag:', error);
    sendTagMutationError(res, error, 'Failed to delete tag');
  }
};
